import React, { useState, useEffect } from 'react'

function CreateRoundConstants({ roundConstantArray }) {
  console.log(roundConstantArray)
  return (
    <div>ROUND CONSTANTS:{roundConstantArray.map((word)=> (<p>{word}</p>))}</div>
  )
}

export default CreateRoundConstants
/*
const [w0, setw0] = useState()
const [w1, setw1] = useState()
const [w2, setw2] = useState()
const [w3, setW3] = useState()
const [w4, setw4] = useState()
const [w5, setW5] = useState()
const [w6, setw6] = useState()
const [w7, setw7] = useState()
const [w8, setW8] = useState()
const [w9, setW9] = useState()
const [w10, setw10] = useState()
const [w11, setw11] = useState()
const [w12, setw12] = useState()
const [w13, setW13] = useState()
const [w14, setw14] = useState()
const [w15, setW15] = useState()
const [w16, setw16] = useState()
const [w17, setw17] = useState()
const [w18, setW18] = useState()
const [w19, setW19] = useState()
const [w20, setw20] = useState()
const [w21, setw21] = useState()
const [w22, setw22] = useState()
const [w23, setW23] = useState()
const [w24, setw24] = useState()
const [w25, setW25] = useState()
const [w26, setw26] = useState()
const [w27, setw27] = useState()
const [w28, setW28] = useState()
const [w29, setW29] = useState()
const [w30, setW30] = useState()
const [w31, setw31] = useState()
const [w32, setw32] = useState()
const [w33, setW33] = useState()
const [w34, setw34] = useState()
const [w35, setW35] = useState()
const [w36, setw36] = useState()
const [w37, setw37] = useState()
const [w38, setW38] = useState()
const [w39, setW39] = useState()
const [w40, setW40] = useState()
const [w41, setw41] = useState()
const [w42, setw42] = useState()
const [w43, setW43] = useState()
const [w44, setw44] = useState()
const [w45, setW45] = useState()
const [w46, setw46] = useState()
const [w47, setw47] = useState()
const [w48, setW48] = useState()
const [w49, setW49] = useState()
const [w50, setW50] = useState()
const [w51, setw51] = useState()
const [w52, setw52] = useState()
const [w53, setW53] = useState()
const [w54, setw54] = useState()
const [w55, setW55] = useState()
const [w56, setw56] = useState()
const [w57, setw57] = useState()
const [w58, setW58] = useState()
const [w59, setW59] = useState()
const [w60, setW60] = useState()

*/